name: CI

on: [pull_request]

concurrency:
  group: "ci-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    uses: ./.github/workflows/test-job.yml
    with:
      runs-on: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test-name: "unit"
      test-command: 'pytest -vv -s -m unit --include-allocation-required tests/'

  integration:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    uses: ./.github/workflows/test-job.yml
    with:
      runs-on: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test-name: "integration"
      test-command: 'pytest -vv -s -m integration --include-allocation-required tests/'

  e2e:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    uses: ./.github/workflows/test-job.yml
    with:
      runs-on: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test-name: "e2e"
      test-command: 'pytest -vv -s -m e2e --include-allocation-required tests/'
